baseurl = "https://urbandatapalette.com/"  # Need trailing slash at start to cover all pages
title = "Urban Data Palette"
theme = "newsroom"
author = "Kenneth Wong"
copyright = "Copyright © Kenneth Wong 2021."
canonifyurls = true

# https://gohugo.io/templates/pagination/
paginate = 200

# If you want to use disqus, uncomment the line below
disqusShortname = "urbandatapalette"

# https://gohugo.io/getting-started/configuration-markup/
[markup]
  [markup.goldmark]
    # Enable raw html
    # https://gohugo.io/news/0.60.0-relnotes/
    [markup.goldmark.renderer]
      unsafe = true
  # Alternatively, you can use chroma instead of pigments
  # to do so comment or delete lines 11 ~ 14 and uncomment lines 17 ~ 27
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    style = "solarized-dark"
    tabWidth = 2


# Enable syntax highlighting
# comment or delete lines 11 ~ 14
# pygmentsCodefences = true
# pygmentsStyle = "solarized-dark"
# pygmentsCodefencesGuessSyntax = true
# pygmentsUseClasses = true
# pygmentsOptions = ""

# ids used below are not valid. Replace with valid ones
[params]
  ga_analytics = "UA-160264012-1" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "@Kenneth_KHW" # twitter handle e.g @weru

  # Create custom css with adding new lines in head.html
  # https://blog.risingstack.com/static-site-generator-hugo-netlify
  # Now changed to override exisiting scss by adding assets folder
  # https://discourse.gohugo.io/t/overriding-theme-styles/18299/2
  # custom_css = ["css/custom-style.css"]

  # mainSections = ["blog", "docs"] #see https://gohugo.io/functions/where/#mainsections
  # uncomment the line below will disable darkmode by default.
  disableDarkMode = true  # note that the UI control for toggling darkmode will remain in place. This way, the user can decide which mode they would like to use while browsing your website
